software: # temp workaround only, using conda build in the future
  hickit: /share/home/ychi/software/hickit/hickit
  k8: /share/home/ychi/software/hickit/k8
  js: /share/home/ychi/software/hickit/hickit.js
  hires: /share/home/ychi/software/hires-utils/hires.py
  hires_index: /share/home/ychi/software/hires-utils/bin_10k_FULL_index
  dip-c: /share/home/ychi/software/dip-c/dip-c
  pairs2con: /share/home/ychi/software/dip-c/scripts/hickit_pairs_to_con.sh
  impute2con: /share/home/ychi/software/dip-c/scripts/hickit_impute_pairs_to_con.sh
  rescale: "/share/home/ychi/software/dip-c/scripts/hickit_3dg_to_3dg_rescale_unit.sh"
  color_file: "/share/Data/ychi/genome/GRCh38.chr.fem.txt"
ref:
  bwa: /share/Data/ychi/genome/GRCh37d5/bwa_mem2_index/genome.fa # bwa_mem2 index file, bwa_mem 1, 2 index not compatible
  snp: /share/Data/ychi/genome/GRCh37d5/GM12878.hg19.snp.tsv
  par: /share/Data/ychi/genome/GRCh37d5/hg19.PAR.bed
  annotation: /share/Data/ychi/genome/GRCh37d5/raw/gencode.v19.annotation.gtf.gz
cpu: # threads using
  bwa: 8
  clean1: 8
  clean2: 8 
# --- labels must change every time ---
ana_home: /share/Data/ychi/repo/task_id # home directory for all result files
sex: female # male | female, sex of sample, required for sam2seg
snp: using # using | *, whether got snp file, required for sam2seg