pep_version: 2.0.0
sample_table: "sample_table.csv"
sample_modifiers:
  append:
    raw: /share/Data/ychi/raw/ # home dir only, real files are in subsamples
    ana_home: /share/Data/ychi/repo/bicell
  derive:
    attribute: [directory]
    sources:
      xqm4: /share/Data/ychi/raw/xqm4/Rawdata/{sample_name}
      xqm3: /share/Data/ychi/raw/xqm3/Rawdata/{sample_name}